### ISSUE TITLE
ModifiedStableDiffusionPipeline in process_data.py

### ISSUE THREAD

**Issue by lyufan** [joycenerd/P4D#5]
Hello! In the file `process_data.py`, line 1 show `from model.modified_stable_diffusion_pipeline import ModifiedStableDiffusionPipeline`, but I found two `modified_stable_diffusion_pipeline.py` file in the directory `model/p4dk` and `model/p4dn`. Which `modified_stable_diffusion_pipeline.py` is used in the `process_data.py` file, and is the dataset different based on different variants?

**Comment by zhiyichin** [comment]
Both files will lead to the same results. The two files differ when optimizing the prompt. We will fix this.

**Comment by lyufan** [comment]
Thank you for your reply!
